Refactor/michaels notes
urbanopt/modelica-fmt pull request #4
Opened 2020-06-11 19:49 UTC by macintoshpie

## Formatting Changes
- put `constrainedby` clause on new line indented (e.g. https://github.com/macintoshpie/modelica-buildings/blob/c2fce7cc11ed217ea7cfa9d1239ed79be8141b16/Buildings/Airflow/Multizone/MediumColumnDynamic.mo#L85)
- put if-then expressions on newlines indented (e.g. https://github.com/macintoshpie/modelica-buildings/blob/c2fce7cc11ed217ea7cfa9d1239ed79be8141b16/Buildings/Airflow/Multizone/BaseClasses/PowerLawResistance.mo#L83)
- put function arguments (named and unnamed) on newlines indented (e.g. https://github.com/macintoshpie/modelica-buildings/blob/format/indent-modifications/Buildings/Fluid/Actuators/Dampers/PressureIndependent.mo#L171)

## Design Changes
- indentation is now tracked using a stack, allowing for the notion of "real/rendered" indentations and ignored indentations. This fixes an issue where multiple rules wanted to be indented at once, and the resulting text was overindented.

## Unaddressed requests
- "break very long lines" (e.g. https://github.com/macintoshpie/modelica-buildings/blob/format/indent-modifications/Buildings/Airflow/Multizone/MediumColumn.mo#L57)
- putting vector elements on newlines (I believe this would relate to the above, as sometimes we want vectors on a single line, I think) (e.g. https://github.com/macintoshpie/modelica-buildings/blob/format/indent-modifications/Buildings/Examples/VAVReheat/Guideline36.mo#L8)

2020-06-11 19:56 UTC, nllong commented on thirdparty/Modelica.g4
> +   | 'if' expression 'then' if_expression_body ('elseif' expression 'then' if_expression_body)* 'else' if_expression_body
I assume that this will need to be updated if we pull in a new grammar. Is there a way to add a comment into the g4 file noting that this has been updated.

2020-06-11 19:57 UTC, nllong requested changes
quick question regarding the changing of g4.

2020-06-12 15:04 UTC, macintoshpie commented on thirdparty/Modelica.g4
> +   | 'if' expression 'then' if_expression_body ('elseif' expression 'then' if_expression_body)* 'else' if_expression_body
Sure, there are actually a couple of places I've tweaked the grammar to make the code less complicated. Would you like me to go back and flag them in the grammar?

2020-06-12 15:05 UTC, nllong commented on thirdparty/Modelica.g4
> +   | 'if' expression 'then' if_expression_body ('elseif' expression 'then' if_expression_body)* 'else' if_expression_body
Yes, I think it will help when we pull in new grammar and look at the diff (assuming people actually look at diffs)... Grazie.

2020-06-18 21:11 UTC, nllong commented on thirdparty/Modelica.g4
> +   // changed from original file
thanks for adding these comments

2020-06-18 21:11 UTC, nllong approved these changes
lvgtm

2020-06-18 21:11 UTC, merged